language: node_js
node_js:
  - "16"
install:
  - npm install -g codecov
  - npm install
script:
  - npm test -- -i && codecov
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f7bf10eff2ba0af12382
    on_success: always
    on_failure: always
    on_start: never
